### ISSUE TITLE
Add how to launch and run the program for beginners

### ISSUE THREAD

**Issue by VedantPol** [Wrap-and-Go/Wrap-nd-Go#13]
[https://github.com/Wrap-and-Go/Wrap-nd-Go/blob/master/README.md](url) change this to help beginners getting started and contribute to the project

**Comment by VedantPol** [comment]
Please Merge pull request #12 .So that I can change the read me file accordingly using the react files  , otherwise, it might be difficult @PratishShrivastava 
thank you :)

**Comment by PratishShrivastava** [comment]
@VedantPol I have merged the PR but if you are planing to make another PR please make a folder and insert all image in it Thank you 👍 (:

**Comment by VedantPol** [comment]
Ya sure will do :)
