### ISSUE TITLE
How to build this project (It is a react, node project) update readme

### ISSUE THREAD

**Issue by VedantPol** [Wrap-and-Go/Wrap-nd-Go#14]
can anyone guide me on how should I launch the program? I forked and cloned the repository. But am unable to launch the file. Please also update the read me on how to  launch this project :) @PratishShrivastava

**Comment by PratishShrivastava** [comment]
@VedantPol to laugh the program type command. (You should have node.js install)

1) npm install (it will download node module)
2) npm start index.js (to start the server)

**Comment by VedantPol** [comment]
ok thanks for the help :)
