### ISSUE TITLE
Upgrade the initial Design of this website

### ISSUE THREAD

**Issue by nayan1xyz** [Wrap-and-Go/Wrap-nd-Go#2]
Pls go through Readme and see the basic design and request us we will give the access for creating.
Pls, note that the best one can be could be taken into consideration. So be Creative

**Comment by oneamanish** [comment]
see my pul req.

**Comment by nayan1xyz** [comment]
@oneamanish we have merged your pull req. but make sure you asked for assigning the issue for you. (as per our organization norms ).

BTW We liked your work. Hope to see u solving more issues for our organization.
