### ISSUE TITLE
Search bar UI Needed 

### ISSUE THREAD

**Issue by nayan1xyz** [Wrap-and-Go/Wrap-nd-Go#7]
The basic design of the search bar is given in the link: https://whimsical.com/food-8PBqBtCftsetbN27UNpFJC 
Just waiting 🤞 Contributor✨

**Comment by nguyenhung15913** [comment]
Hi, Can I work on this?

**Comment by nayan1xyz** [comment]
Yes, Go Ahead @nguyenhung15913 ✨

**Comment by nayan1xyz** [comment]
@nguyenhung15913  We have updated our site into components. So you can add your code inside [Main Code](https://github.com/Wrap-and-Go/Wrap-nd-Go/blob/master/src/components/Page.jsx).

**Comment by nayan1xyz** [comment]
@nguyenhung15913  Also you can add CSS code inside [Style.css](https://github.com/Wrap-and-Go/Wrap-nd-Go/blob/master/public/style.css)

**Comment by PratishShrivastava** [comment]
@nguyenhung15913 there is some error in your code please check again and send pr with a different branch

**Comment by nayan1xyz** [comment]
We need a search bar in our website. 
For Reference [Design](https://whimsical.com/food-8PBqBtCftsetbN27UNpFJC) 
Thankyou ✨
