### ISSUE TITLE
Separate the components

### ISSUE THREAD

**Issue by PratishShrivastava** [Wrap-and-Go/Wrap-nd-Go#8]
Separate the components of the page like navbar, main and footer 

[Click Here](https://github.com/Wrap-and-Go/Wrap-nd-Go/blob/master/src/components/Page.jsx)

**Comment by VedantPol** [comment]
hey, @PratishShrivastava I would like to work on this issue. can you elaborate on what you meant by Separate :)

**Comment by ZaidKhan144** [comment]
@PratishShrivastava I could do this if you could assign me.

**Comment by nayan1xyz** [comment]
> hey, @PratishShrivastava I would like to work on this issue. can you elaborate on what you meant by Separate :)

Yes go-ahead @VedantPol 
pls Note:  send pr with a different branch name

**Comment by nayan1xyz** [comment]
> @PratishShrivastava I could do this if you could assign me.

@ZaidKhan144  Yes go-ahead
pls, Note: send pr with a different branch name.

**Comment by nayan1xyz** [comment]
> hey, @PratishShrivastava I would like to work on this issue. 

"**Can you elaborate on what you meant by Separate**" :)
> 

1. You have to separate the code [Page.jsx](https://github.com/Wrap-and-Go/Wrap-nd-Go/blob/master/src/components/Page.jsx) into Header, Body, Footer by separating out different components. 

2.  Send the pr with a different branch name.

**Comment by ZaidKhan144** [comment]
@nayan1xyz, thanks for assigning. I'm on it.
